// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
// import StoreProvider from "@/store/storeProvider";
// import { AppRouterCacheProvider } from "@mui/material-nextjs/v15-appRouter";
// import { ToastContainer } from "react-toastify";
// import NavigationTracker from "@/components/shared/NavigationTracker";
//  import { ThemeProvider } from '@mui/material/styles';
// import theme from "./theme";
import { Outfit } from "next/font/google";
import { SidebarProvider } from "@/context/SidebarContext";
import { ThemeProvider } from "@/context/ThemeContext";
// const geistSans = Geist({
//     variable: "--font-geist-sans",
//     subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//     variable: "--font-geist-mono",
//     subsets: ["latin"],
// });

// export const metadata: Metadata = {
//     title: "Create Next App",
//     description: "Generated by create next app",
// };
const outfit = Outfit({
    subsets: ["latin"],
});
export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            {/* <StoreProvider> */}
                <body
                    className={`antialiased ${outfit.className} dark:bg-gray-900`} //${geistSans.variable} ${geistMono.variable}
                >
                    <ThemeProvider>
                            <SidebarProvider>{children}</SidebarProvider>
                        </ThemeProvider>
                    {/* <AppRouterCacheProvider options={{ enableCssLayer: true }}>
                        

                        <NavigationTracker />
                        <ToastContainer />
                    </AppRouterCacheProvider> */}
                </body>
            {/* </StoreProvider> */}
        </html>
    );
}
